### ISSUE TITLE
Add checksum to file transfers before local deletion

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/voxel#33]
Is your feature request related to a problem? Please describe.
File transfers are currently susceptible to corruption during transfer with no logic checking

Describe the solution you'd like
Add checksum on local vs external file before local deletion

Acceptance Criteria

- [ ] Check sum implemented and unit tested in simulated mode to be working properly.

**Comment by adamkglaser** [comment]
Implemented in #46

**Comment by micahwoodard** [comment]
Pull request still not merged
